### PR TITLE
fix when onInterest is a calleable object

### PR DESCRIPTION
**Pull request by pedosb**

### CODE REVIEW

**Comment by jefft0** [comment]
Hello Pedro. Can you give an example of a callable object which needs this fix?

**Comment by jefft0** [comment]
Hi again Pedro. The code in question is no for calling getOnInterest() but only for checking the number of arguments. This is to decide which form of the callback to use. I'll wait a few more days to see if you have questions. If I don't hear from you, I plan to close this pull request without change.

**Comment by pedosb** [comment]
Sorry, I lost your first comment in my emails. Yes I can give an example. The following code needs this patch to work.

```python
import time
import json
import pyndn
import pyndn.security
import logging

class SimpleProvider(object):

    def __init__(self, keyChain, certificateName):
        self.keyChain = keyChain
        self.certificateName = certificateName

    def __call__(self, prefix, interest, face, interestFilterId,
                 ndnFilter):
        logging.debug("Received interest for %s" % interest.getName())

        data = pyndn.Data(interest.getName())
        info = pyndn.MetaInfo()

        data.setContent(json.dumps(dict(data="hello")).encode("utf-8"))

        info.setFreshnessPeriod(0)
        data.setMetaInfo(info)
        self.keyChain.sign(data, self.certificateName)

        face.putData(data)

if __name__=='__main__':
    logging.basicConfig(level=logging.DEBUG)

    face = pyndn.Face()
    keyChain = pyndn.security.KeyChain()
    face.setCommandSigningInfo(keyChain, keyChain.getDefaultCertificateName())

    provider = SimpleProvider(
        keyChain, keyChain.getDefaultCertificateName())

    face.registerPrefix(pyndn.Name("/my/hello"),
                        provider,
                        None)

    while True:
        face.processEvents()
        time.sleep(0.001)
```

**Comment by jefft0** [comment]
Hi Pedro. Is it possible for you to change

    face.registerPrefix(pyndn.Name("/my/hello"),
                        provider,
                        None)

to

    face.registerPrefix(pyndn.Name("/my/hello"),
                        provider.__call__,
                        None)

**Comment by pedosb** [comment]
Yes it is, but I personally find the first approach (with the patch) more generic and a easier to read code. Anyways that also solves the problem.

**Comment by jefft0** [comment]
I agree that yours it the best approach when onInterest is a callable object, but it only works in that case. When onInterest is a method or function it doesn't work. The best solution is for the library to check if onInterest is a callable object, but I couldn't find code for this. Do you know how Python can check if onInterest is a callable object vs. a function or method?

**Comment by pedosb** [comment]
Sorry about that, I considered that it worked for all cases. Anyways I added a new patch that test for method and function maybe that could be used. I tested it with:

```python
import time
import json
import pyndn
import pyndn.security
import logging

class SimpleProvider(object):

    def __init__(self, keyChain, certificateName):
        self.keyChain = keyChain
        self.certificateName = certificateName

    def __call__(self, prefix, interest, face, interestFilterId,
                 ndnFilter):
        logging.debug("Received interest for %s" % interest.getName())

        data = pyndn.Data(interest.getName())
        info = pyndn.MetaInfo()

        data.setContent(json.dumps(dict(data="hello")).encode("utf-8"))

        info.setFreshnessPeriod(0)
        data.setMetaInfo(info)
        self.keyChain.sign(data, self.certificateName)

        face.putData(data)

def function_provider(prefix, interest, face, interestFilterId,
             ndnFilter):
    logging.debug("Received interest for %s" % interest.getName())

    data = pyndn.Data(interest.getName())
    info = pyndn.MetaInfo()

    data.setContent(json.dumps(dict(data="hello")).encode("utf-8"))

    info.setFreshnessPeriod(0)
    data.setMetaInfo(info)
    keyChain.sign(data, certificateName)

    face.putData(data)

if __name__=='__main__':
    logging.basicConfig(level=logging.DEBUG)

    face = pyndn.Face('localhost')
    keyChain = pyndn.security.KeyChain()
    face.setCommandSigningInfo(keyChain, keyChain.getDefaultCertificateName())
    certificateName = keyChain.getDefaultCertificateName()

    provider = SimpleProvider(
        keyChain, certificateName)

    face.registerPrefix(pyndn.Name("/my/hello1"),
                        provider,
                        None)
    face.registerPrefix(pyndn.Name("/my/hello2"),
                        provider.__call__,
                        None)
    face.registerPrefix(pyndn.Name("/my/hello3"),
                        function_provider,
                        None)

    while True:
        face.processEvents()
        time.sleep(0.001)
```

**Comment by jefft0** [comment]
Thanks for the nice solution. I merged it.

**Pull request merged**
