### PR TITLE
Add Tlv0_3WireFormat and make it the default

### PR DESCRIPTION
**Pull request by jefft0**
To resolve https://redmine.named-data.net/issues/4988, add the class `Tlv0_3WireFormat` to support wire format v0.3, and make it the default wire encoding.

This pull request also includes the following improvements from @Pesa :

* Update `.gitignore` patterns: most notably, ignore python3's `__pycache__` folder, Visual Studio Code's `.vscode` folder, and several other files created by pip/setuptools.
* Fix pytest warning: pytest treats all classes whose name starts with "Test" as test cases, but then complains because it doesn't expect test classes to have a `__init__` method. So we prepend an underscore to `TestValidationResult` to make it clear that it's a private helper and not a test case.
* Fix DeprecationWarning with Python 3.7: see the commit message.
* Modernize setup.py: declare all dependencies in `setup.py`, including those for "extras" (I defined two of them: test and doc). The `mmh3` dependency was not declared before, it's now mandatory. If that's not desirable, I can define another "extra feature" for psync that pulls in the additional dependency, but given that `mmh3` is pretty small I don't think that's necessary. I'm not sure why the documentation build process uses such an old version of sphinx but I kept that unchanged for now. This commit also adds a `pytest.ini` config file so that you can just type `pytest`/`pytest-3` from the root of the repo and it will automatically run all unit tests.
* Add CI via Travis: this one should be pretty obvious.

### CODE REVIEW

**Comment by jefft0** [comment]
@Pesa , to make this pull request, I cherry picked your updates from pull request #8 to update setup.py, etc. Then I added support for wire format v0.3 and made it the default in the same way it is done in jNDN and ndn-cpp.

Please let me know if this works for you. If so we can merge this pull request and close #8. Thanks.

**Comment by Pesa** [comment]
Works for me, thanks.

**Comment by Pesa** [comment]
@jefft0 I see that v2.13beta1 has been released on PyPI. Can you please update the version in `setup.py` and `CHANGELOG` to match? Thanks.

**Comment by jefft0** [comment]
I thought I did. It's on my local copy. Maybe I didn't push to the right branch. (My local setup.py was right when I released to PyPi.)

**Comment by Pesa** [comment]
yeah, looks like that commit is only in the `wire-format-v0.3` branch, not in master.

**Comment by Pesa** [comment]
ping?

**Comment by jefft0** [comment]
I merged my local copy of the pull request branch to master and pushed. This included this commit:
https://github.com/named-data/PyNDN2/releases/tag/v2.13beta1

Then I updated the tag for this release:
https://github.com/named-data/PyNDN2/releases/tag/v2.13beta1

**Comment by Pesa** [comment]
Thanks!

**Pull request merged**
