### PR TITLE
support for packet format 0.3 in PyNDN2

### PR DESCRIPTION
**Pull request by tuple71**
1. remove selector
2. add hoplimit
3. create tlv_0_3_wire_format
4. add CanBePrefix
5. change unittest(interest/data)
6. change escape ~ instead of +

### CODE REVIEW

**Comment by Pesa** [comment]
See also #8

**Review by mateus-n00b — COMMENTED** [review]
Hey, nice work! However, I notice that when I call registerPrefix it raises the same error from TLV 0.2 (type 9). The problem is related to the line 100 in node.py (and further to the Interest packet encoding):  
       98 commandInterest = Interest()
        99 commandInterest.setCanBePrefix(True)
        100 # commandInterest.setMustBeFresh(True) # must be commented to work properly 

I guess that the interest should encoding should be updated as well.

BR

**Comment by Pesa** [comment]
> 100 # commandInterest.setMustBeFresh(True) # must be commented to work properly

This doesn't seem the proper fix. Have you tried with https://github.com/named-data/PyNDN2/pull/8 ?

In any case, this library isn't being developed anymore, please use https://github.com/named-data/python-ndn instead.

**Comment by mateus-n00b** [comment]
Hi, Davide! Actually was a workaround from a newbie in pyndn :D. I really
appreciate your answer. It will be very helpful.

BR.

Em sáb, 26 de dez de 2020 4:46 PM, Davide Pesavento <
notifications@github.com> escreveu:

**Comment by jefft0** [comment]
Hi @mateus-n00b . Pull request #11 has been merged which has similar changes. The unit tests also run. Please pull the latest from GitHub or PyPi. Does it work for you?

**Pull request closed without merging**
