### PR TITLE
Switch default Interest encoding to packet format v0.3

### PR DESCRIPTION
**Pull request by Pesa**
https://redmine.named-data.net/issues/4988

Plus a few other improvements:
* Update `.gitignore` patterns: most notably, ignore python3's `__pycache__` folder, Visual Studio Code's `.vscode` folder, and several other files created by pip/setuptools.
* Fix pytest warning: pytest treats all classes whose name starts with "Test" as test cases, but then complains because it doesn't expect test classes to have a `__init__` method. So we prepend an underscore to `TestValidationResult` to make it clear that it's a private helper and not a test case.
* Fix DeprecationWarning with Python 3.7: see the commit message.
* Modernize setup.py: declare all dependencies in `setup.py`, including those for "extras" (I defined two of them: test and doc). The `mmh3` dependency was not declared before, it's now mandatory. If that's not desirable, I can define another "extra feature" for psync that pulls in the additional dependency, but given that `mmh3` is pretty small I don't think that's necessary. I'm not sure why the documentation build process uses such an old version of sphinx but I kept that unchanged for now. This commit also adds a `pytest.ini` config file so that you can just type `pytest`/`pytest-3` from the root of the repo and it will automatically run all unit tests.
* Add CI via Travis: this one should be pretty obvious.

### CODE REVIEW

**Comment by jburkeucla** [comment]
@jefft0 Can you please review and merge?

**Comment by Pesa** [comment]
> This seems to include many other changes than the packet format update. Please detail other changes.

Yes it contains other changes. Each logical change is a separate commit and each commit says what it's about. They should all be pretty uncontroversial, except maybe "Modernize setup.py". Let me know if you have specific questions on any of them.

**Comment by jburkeucla** [comment]
@Pesa Yes, referring to the commit log is fine.  Thanks.

**Comment by Pesa** [comment]
Oh, I just noticed that github made a mess of the commit series. Apparently it reordered them based on git's "author date" instead of being in the order I wanted them. Let me rebase the patch series.

**Comment by Pesa** [comment]
@cawka @yoursunny

**Comment by Pesa** [comment]
@jburkeucla I expanded the PR description with details of the other changes.

**Comment by jburkeucla** [comment]
Thanks, looks good to me.  Please have new owner (or whoever) merge.

**Comment by Pesa** [comment]
I forgot two things.

* One integration test fails when run against current NFD from got, something with prefix registration, I haven't investigated. However that test was also failing before my changes, so it's not a regression.
* I haven't touched the C extension module. My understanding is that it's a copy of ndn-cpp, so when ndn-cpp switches to v0.3 we can simply update the bundled copy. Let me know if this should be dealt with differently.

**Comment by Pesa** [comment]
@cawka ping?

**Comment by jefft0** [comment]
Similar changes were made in pull request #11 which has been merged. See details there. Closing this.

**Pull request closed without merging**
